/*
 * Copyright (c) 2016-2025 Daniel Ennis (Aikar) - MIT License
 *
 *  Permission is hereby granted, free of charge, to any person obtaining
 *  a copy of this software and associated documentation files (the
 *  "Software"), to deal in the Software without restriction, including
 *  without limitation the rights to use, copy, modify, merge, publish,
 *  distribute, sublicense, and/or sell copies of the Software, and to
 *  permit persons to whom the Software is furnished to do so, subject to
 *  the following conditions:
 *
 *  The above copyright notice and this permission notice shall be
 *  included in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 *  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 *  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 *  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 *  WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package co.aikar.commands;

import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerLocaleChangeEvent;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.util.Locale;

class ACFBukkitLocalesListener implements Listener {

    private final BukkitCommandManager manager;
    private MethodHandle localeMethod1_8 = null;
    private boolean checkedLocaleMethod1_8 = false;

    ACFBukkitLocalesListener(BukkitCommandManager manager) {
        this.manager = manager;
    }

    @EventHandler
    void onLocaleChange(PlayerLocaleChangeEvent event) {
        if (!manager.autoDetectFromClient) {
            return;
        }
        Player player = event.getPlayer();
        Locale locale = null;
        try {
            locale = event.locale();
        } catch (NoSuchMethodError ignored) {
            try {
                if (!event.getLocale().equals(manager.issuersLocaleString.get(player.getUniqueId()))) {
                    locale = ACFBukkitUtil.stringToLocale(event.getLocale());
                }
            } catch (NoSuchMethodError ignored2) {
                try {
                    if (!checkedLocaleMethod1_8) {
                        checkedLocaleMethod1_8 = true;
                        MethodHandles.Lookup lookup = MethodHandles.lookup();
                        MethodType type = MethodType.methodType(String.class);
                        localeMethod1_8 = lookup.findVirtual(PlayerLocaleChangeEvent.class, "getNewLocale", type);
                    }
                    if (localeMethod1_8 != null) {
                        String value = (String) localeMethod1_8.invoke(event);
                        if (!value.equals(manager.issuersLocaleString.get(player.getUniqueId()))) {
                            locale = ACFBukkitUtil.stringToLocale(value);
                        }
                    }
                } catch (Throwable t) {
                    manager.log(LogLevel.ERROR, "Error registering MethodHandle for LocaleChangeEvent", t);
                }
            }
        }
        if (locale == null) {
            return;
        }
        manager.setPlayerLocale(player, locale);
    }
}
